version: "1.1.2-{build}"

branches:
  only:
    - master

os: Windows Server 2012 R2

environment:
  GOPATH: c:\gopath

init:
  - SET PATH=%GOPATH%\bin;%PATH%
  - git config --global core.autocrlf input

install:
  - go version
  - go env
  - mkdir %GOPATH%
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u github.com/tischda/go2xunit

build_script:
  - build.bat

test_script:
  - pokenv.exe -version
  - go test -v -cover
  - go test -v | go2xunit -xunitnet > xunit-report.xml
  - pokenv.exe -hkcu data\multivars.txt
  - pokenv.exe -hkcu data\testvars-pass.txt
  - pokenv.exe -hkcu data\delvars.txt

artifacts:
  - path: pokenv.exe
    name: Pokenv

deploy: off

on_finish:
- ps: >-
    If (Test-Path .\xunit-report.xml) {
      (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\xunit-report.xml))
    }
