version: "1.1.1-{build}"

branches:
  only:
    - master

  except:
    - gh-pages

os: Windows Server 2012 R2

#environment:
#  GOPATH: c:\gopath

init:
- git config --global core.autocrlf input

install:
  - go version
  - go env
  - mkdir c:\gopath
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u github.com/tischda/go2xunit
  
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - go build -o pokenv.exe

test_script:
  - go test -v -cover
  - go test -v | go2xunit -xunitnet > xunit-report.xml
  - pokenv.exe -version
  - pokenv.exe -hkcu data\multivars.txt
  - pokenv.exe -hkcu data\testvars-pass.txt
  - pokenv.exe -hkcu data\delvars.txt

artifacts:
  - path: pokenv.exe
    name: Pokenv

deploy: off

on_finish:
- ps: >-
    If (Test-Path .\xunit-report.xml) {
      (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\xunit-report.xml))
    }
