branches:
  only:
    - master

image: Visual Studio 2019

environment:
  GOPATH: C:\gopath
  GOPROXY: https://proxy.golang.org  

init:
  - SET PATH=%GOPATH%\bin;%PATH%

install:
  - go version
  - go env
  - go install github.com/tebeka/go2xunit@latest

build_script:
  - for /f "delims=" %%a in ('git describe --tags') do @set version=%%a
  - ps: Update-AppveyorBuild -Version $env:version
  - go build -mod vendor -ldflags=all="-X main.version=%version% -s -w"

test_script:
  - pokenv.exe -version
  - go test -v -cover
  - go test -v | go2xunit -xunitnet > xunit-report.xml

#  This hangs the build, disabling for now...
#
#  - pokenv.exe -f data\multivars.txt
#  - pokenv.exe -f data\testvars-pass.txt
#  - pokenv.exe -f data\delvars.txt

artifacts:
  - path: pokenv.exe
    name: Pokenv

deploy: off

on_finish:
- ps: >-
    If (Test-Path .\xunit-report.xml) {
      (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\xunit-report.xml))
    }
